[FEAT] Presentation View Custom Menu Button 추가 (#52)
DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth pull request #59
Opened 2022-07-27 10:15 UTC by jeong-hyeonHwang

### ⚠️#52참고⚠️

### 변경사항 요약
- 발표자 화면의 우상단에 위치하는 Expanded Button과 관련된 View 추가
- Expanded Button 펼칠 시 등장하는 세 가지의 버튼 터치 시 전환되는 뷰와 관련된 코드가 들어가는 곳에 테스트 Print문 추가
- divider, close button color asset 추가

2022-07-27 10:51 UTC, User-Lawn approved these changes
지곡회관에서 친절한 설명 감사합니다. 적용해서 PresentationView를 완성해보겠습니다.

2022-07-27 10:53 UTC, jeong-hyeonHwang commented
파이팅!!!!! 빠른 어프룹 감사합니다 🔥🔥🔥🔥🔥

2022-07-27 13:23 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +            .overlay(dividerColor)
overlay로 적용하는것과 foreground로 적용하는것의 차이가 어떤게 있을까요?
왜 오버레이를 선택하셨는지도 궁금합니다! 오버레이를 잘 안써봐서 궁금해요 ㅎㅎ

2022-07-27 13:25 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +                break
액션 이렇게 설정하니 깔끔하군요! 리펙토링시 참고하겠습니다~ 
👍👍

2022-07-27 13:26 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +                .font(.system(size: fontSize))
시스템 폰트의 이름을 직접 작성하는게 좋을것 같아요!
iOS기준 12 포인트에 해당하는것은 .Caption 입니다~

2022-07-27 13:28 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        .frame(width:64, height: 24)
각 버튼의 폭을 고정한것은 이해가 되는데, 높이값도 따로 정해준 이유가 있을까요?

2022-07-27 13:29 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +    private let defaultTextColor = Color.white
잊지않고 프라이빗 설정한것 멋져용!

2022-07-27 13:34 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +        PresentationMenuView(deviceName: testTxt.count > txtMaxLength ? testTxt.substring(from: 0, to: txtMaxLength) : testTxt)
섭스트링이 뷰 내부에서 구현되었는데, 프리뷰에서 다시 구현한 이유가 있을까요?

2022-07-27 13:37 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .fixedSize(horizontal: false, vertical: true)
오.. 이런것도 있군요

2022-07-27 13:38 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .font(.system(size: 17))
17pt는 .body 입니다.
default라서 따로 설정하지 않아도 됩니다!

2022-07-27 13:41 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        .frame(width:64, height: 24)
디자인상 디바이더 높이를 고정하기 위함이군요.
높이의 용도를 명확히 하기 위해 위쪽 디바이더를 묶는 바디부분에 적용되면 좋겠다고 생각을 해봤지만.. 바디는 적용이 불가능하니..
쩝..

2022-07-27 13:51 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +            .overlay(dividerColor)
Text나 Image 같은 경우에는 foreground를 통한 Color Setting이 가능한데 Divider의 경우에는 foreground로 색상 설정 시 색상이 반영되지 않는 문제가 있어 overlay를 사용했습니다 :D
+) 추가적으로 background를 통한 색상 설정이 가능한 것 같아요!

2022-07-27 13:52 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                        }.animation(.spring(), value: scale)
무엇을 위한 에니메이션일까요? 지금 동작을 안하고 있는것 같습니다!
둘다 적용할때를 위해서
withAnimation을 이용해보는건 어떤가요?
로운이 에니메이션 전문가에요~!
isExpanded.toggle을 withAnimation으로 씌우면 관련해서 if문이 돌아가는 부분에 에니메이션이 전체적으로 동일하게 적용될것입니다.
---
만약 스케일부분을 0 -> 1로 바꾸는 방식으로 에니메이션을 고려했다면, 스케일 변화도 삼항연산자를 넣어야할듯합니다. 다만 적용 위치가 다른것 같아요! 최종적으로 그방식으로 에니메이션을 그린다면 if문에서 그리냐 마냐로 결정하기보단 가로방향 스케일을 적용하는게 맞을것 같아요!
---
저는 zstack으로 뒤에 숨기는것도 재미있는 방법이라고 생각합니다!
에니메이션적 완성도가 더 높아질것 같아요.(물론 고생하는 방법이기도 합니다)

2022-07-27 13:53 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                HStack(spacing: 0) {
스페이서와 hstack만 있기 때문에 스페이서를 따로 설정해주는건 필요하지 않아보입니다!

2022-07-27 13:56 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                                .frame(width: buttonWH, height: buttonWH)
메뉴와 icn_chevron_right_32px 아이콘의 크기가 디자인과 일치하지 않는데, 
로운과 이야기된건지 궁금합니다.

2022-07-27 13:57 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +                .font(.system(size: fontSize))
반영했습니다! 👍

2022-07-27 13:57 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .font(.system(size: 17))
반영했습니다! 👍

2022-07-27 13:57 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .padding([.vertical], 8)
패딩과의 사투가 느껴집니다.. 승리하세요.. 화이팅 👍

2022-07-27 13:58 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +            .padding([.top])
.padding(.top) 으로도 적용된답니다!

2022-07-27 14:00 UTC, song-cool requested changes
쓰다보니.. 너무 오래썼네요..
확장되는 네비게이션이 확실히 어려운것 같아요!
조금만 더 힘내보아요! 화이팅 🔥

2022-07-27 14:02 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +            .overlay(dividerColor)
오 하나 배워갑니다~ 저도 안되는건 오버레이로 해결봐야겠어요

2022-07-27 14:04 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .fixedSize(horizontal: false, vertical: true)
어떤 이유에서 사용한지 궁금합니다!

2022-07-27 14:05 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +        PresentationMenuView(deviceName: testTxt.count > txtMaxLength ? testTxt.substring(from: 0, to: txtMaxLength) : testTxt)
오 프리뷰에서 먼저 테스트해보다가 코드 옮기면서 지우지 않은 것 같아요! 수정했습니다!🔥

2022-07-27 14:06 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                HStack(spacing: 0) {
반영했습니다!
+) 추후 PresentationView에 편입될 것을 고려해, VStack -> Zstack 구조에서 ZStack -> VStack으로 변경했습니다

2022-07-27 14:11 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        .frame(width:64, height: 24)
방금 확인해보니 Text값 자체를 고정된 값으로 지정 후 Rectangle을 overlay시키는 형태라 height가 없어져도 동일한 형태가 제공되어, height는 삭제했습니다👍

2022-07-27 14:17 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                                .frame(width: buttonWH, height: buttonWH)
앗...! 28 -> 32로 변경 후 반영했습니다! 🔥

2022-07-27 14:52 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                        }.animation(.spring(), value: scale)
**:::1:::**
line32의 코드
```
.animation(.spring(), value: scale)
```
의도치 않은 애니메이션이 맞습니다 ㅎ... 여러가지를 테스트하다 삭제하는 걸 잊었습니다... 다음부턴 주의하겠습니다!🔥

**:::2:::**
<img width="443" alt="스크린샷 2022-07-27 오후 11 43 10" src="https://user-images.githubusercontent.com/96641477/181276807-3d679f3e-7746-4a01-bfb3-50b4eacbfdc1.png">

withAnimation 사용 제안 감사합니다! 👍
기존의 코드에서는 텍스트 자체는 깜빡이는 수준에 불과해 Rectangle의 변화를 먼저 인지하여 텍스트의 애니메이션 효과가 없는 것을 체감하지 못했었습니다.
withAnimation으로 isExpanded 프로퍼티와 연관된 코드에 전체적으로 애니메이션을 동일하게 적용하는 형태로 테스트한 결과, Rectangle의 width 변화보다 Close 버튼의 색상 흐려짐이 먼저 인식되어 버튼 사이즈 조절 애니메이션이 부자연스럽게 보여 결론적으로 withAnimation은 적용하지 않았습니다.

**:::3:::**
확실히 zstack을 사용하면 기존의 방식이 지니던 텍스트 애니메이션 효과의 부재를 해결할 수 있을 것 같습니다. 공수 시간이 살짝 남은 관계로 한 번 만들어보겠습니다! 🔥🔥🔥🔥🔥

2022-07-27 15:11 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                HStack(spacing: 0) {
구웃!

2022-07-27 15:15 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .padding([.vertical], 8)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/46256034/181284057-84e41a27-321b-464e-86b4-58c78003e23f.png">
높이값이 맞지 않는것을 보니.. 싸움이 아직 남았군요 호호..

2022-07-27 15:16 UTC, song-cool commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                        }.animation(.spring(), value: scale)
:::3::: 말고도 :::2:::에서 시도하려했던 스케일을 활용하는것도 좋아보입니다. 다만 y축 스케일 조절이 되는지 해본적이 없어서 확인이 필요할것 같습니다!

2022-07-27 15:17 UTC, song-cool requested changes
리졸브 되지 않은 커멘트들 한번 더 확인 부탁드려요!

2022-07-27 15:36 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .fixedSize(horizontal: false, vertical: true)
```
Text(deviceName.count > txtMaxLength ? deviceName.substring(from: 0, to: txtMaxLength) : deviceName)
    .fixedSize(horizontal: false, vertical: true)
```
1. Text ... 이하 코드는 Custom Menu의 width값 자체에 제한을 두는 형태가 아닌 글자 수 제한을 통해 width 제한을 두는 형태로 작성된 코드입니다.
2. fixedSize ... 이하 코드는 텍스트 양이 많아질 때 수직방향으로 여러 텍스트가 내려가는 것을 방지하기 위해 vertical fix를 시키는 코드였습니다. 다만, 1의 방법을 통해 텍스트 길이가 제한되는 걸 감안했을 때 삭제해도 될 것 같아, 현재 삭제한 상태입니다! 👍

2022-07-27 17:09 UTC, woo0dev approved these changes
점점 코드를 보기 편해지는게 느껴지는 거 같습니다!! 역시 갓엘리제🤩🤩🤩
고생하셨습니다!! 오늘 밤도 화이팅!!

2022-07-27 20:42 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                            .padding([.vertical], 8)
Figma와 Zeplin 상에서는 40이지만 어제 오후 전달받은 내용은 44였던 것 같아, 높이값 44로 반영했습니다! 다시 한 번 확인 후 다르다면 반영하겠습니다 🔥

2022-07-27 20:45 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +                        }.animation(.spring(), value: scale)
**:::2:::** scaleEffect와 withAnimation을 통한 구현 완료 했습니다! 🔥🔥🔥🔥🔥

2022-07-28 05:17 UTC, unnnyong commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +    var dividerColor: Color
변수가 아닌 정수여야할까요 ?

2022-07-28 05:22 UTC, unnnyong commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        PresentationMenuButtonView(buttonName: "CLOSE", buttonTextColor: closeButtonColor,transferViewType: MenuButtonViewType.close)
MenuButtonViewType enum의 Associated Values로ㅓ button name, text color까지 관리하면 어떨까요 ?

```swift
enum MenuButtonViewType {
    case close
    case vote
    case qAndA

    var Name: String {
        switch self {
        case .close: return "CLOSE"
        case .vote: return "VOTE"
        case .type
    }
}
```

2022-07-28 05:22 UTC, unnnyong commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        PresentationMenuButtonView(buttonName: "CLOSE", buttonTextColor: closeButtonColor,transferViewType: MenuButtonViewType.close)
@viewBuilder 를 활용하면 enum에서 각각의 View도 만들 수 있지 않을까 합니다 .. !

2022-07-28 05:23 UTC, unnnyong commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +                break
```suggestion
```

각각의 case에 break를 삭제해도 될 것 같아요 ~

2022-07-28 05:24 UTC, unnnyong commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +    private let txtMaxLength = 18
길이는 width를 이야기하는걸까요 ? 문자열의 갯수를 이야기하는 것일까요 ?
조금 더 뚜렷하게 명명되면 좋을 것 같아요 ~

2022-07-28 06:32 UTC, song-cool approved these changes

2022-07-28 06:33 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +    var dividerColor: Color
오 뷰에서 뷰로 넘길 때에도 let으로 선언해도 되는군요! 알려주셔서 감사합니다 영👍👍👍

2022-07-28 06:49 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuButtonView.swift
> +        PresentationMenuButtonView(buttonName: "CLOSE", buttonTextColor: closeButtonColor,transferViewType: MenuButtonViewType.close)
제안 감사합니다!  button name, text color 둘 다 computed property로 변경했습니다! 👍👍👍
@viewBuilder를 활용한 형태는 리팩토링 백로그로 남겨두겠습니다! 🔥🔥🔥🔥🔥

2022-07-28 06:52 UTC, jeong-hyeonHwang commented on Pikipick/Pikipick/PresentationMenu/PresentationMenuView.swift
> +    private let txtMaxLength = 18
txtMaxLength -> txtMaxCount로 변경했습니다!  리뷰 감사합니다!!! :D~!~~~

2022-07-28 06:53 UTC, jeong-hyeonHwang commented
많은 분들의 리뷰로 코드가 개선되었습니다!!!!
Merge할 수 있어서 너무 행복해요...☺️
감사합니다 @unnnyong @song-cool @User-Lawn @woo0dev

2022-07-28 06:53 UTC, merged